
.ansible:
  image: python:3.12-slim
  before_script:
    - pip install --quiet ansible-core ansible-lint
  
ansible-lint:
  extends: .ansible
  stage: validate
  script:
    - ansible-playbook k3sCI/ansible/k3s-cluster.yml --syntax-check # Unmatched host patterns warnin
    - ansible-lint k3sCI/ansible/
  allow_failure: true
