# Example for Playbook

---

- name: First Play # Set name 
  hosts: ajtest-machine # Target all machines
  become: true # Enables sudo permission
  tasks: # What to do

    - name: Ping # Ping the machine
      ansible.builtin.ping: # Ansible built in module

    - name: Upgrade all packages 
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

    - name: Install DCSS
      ansible.builtin.apt:
        name:
          - crawl
        state: present

    - name: Set Timezone to Sweden
      become: true
      community.general.timezone:
        name: Europe/Stockholm

    - name: Create User
      ansible.builtin.user:
       name: axel
       create_home: true   
        
